# Generated by Django 2.1.3 on 2018-11-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
