# Generated by Django 2.1.3 on 2018-11-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0002_office_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='number_of_seats',
        ),
    ]
