# Generated by Django 2.1.3 on 2018-12-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0004_auto_20181201_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
