# Generated by Django 2.1.3 on 2018-12-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0006_reservation_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desks', to='reserve_app.Office'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reserve_app.Desk'),
        ),
    ]
