# Generated by Django 2.1.3 on 2018-12-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0007_auto_20181204_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='desk',
            unique_together={('number', 'office')},
        ),
    ]
